name: nepal_air_quality
description: Real-time air quality monitoring for Nepal cities with EPA AQI standards
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  mapbox_maps_flutter: ^2.3.0
  geocoding: ^2.1.1
  
  # UI Components & Navigation
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  go_router: ^12.1.3
  
  # Notifications & Background
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.6
  flutter_background_service: ^2.4.1
  flutter_background_service_android: ^2.4.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # App Configuration
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/